In [1]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
import pickle
import os, sys
# Hides output while after model learned
from IPython.display import clear_output
#set path
sys.path.insert(1, '../')

from utils.config_reader import config_reader
# Import parameters
config = config_reader('../config/config.json')
random_state = config.random_seed
path_models = config.path_models

In [2]:
# загружаем данные
X, y = fetch_california_housing(return_X_y=True) #load_boston(return_X_y=True) #as_frame=True,
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=random_state)
print(X_train.shape, X_test.shape)

# обучаем модель
model = LinearRegression()
model.fit(X_train, y_train)

# делаем инференс моделью на тесте
test_pred = model.predict(X_test)
print('sklearn model predict:\n', test_pred)


(16512, 8) (4128, 8)
sklearn model predict:
 [0.71912284 1.76401657 2.70965883 ... 4.46877017 1.18751119 2.00940251]


In [3]:
# Save the model
with open(os.path.join(path_models + 'model.pkl'), 'wb') as output:
    pickle.dump(model, output)

In [4]:
path_models

'../models/'

In [5]:
# recover saved model
with open(os.path.join(path_models + 'model.pkl'), 'rb') as f:
    model_r = pickle.load(f)

In [6]:
# делаем инференс моделью на тесте
test_pred = model_r.predict(X_test)
print('sklearn model predict:\n', test_pred)

sklearn model predict:
 [0.71912284 1.76401657 2.70965883 ... 4.46877017 1.18751119 2.00940251]


In [7]:
res = [] 
for i in range(X_test.shape[0]):
    res.append(model_r.predict(X_test[i,:].reshape(1,-1))[0])  
np.array(res)

array([0.71912284, 1.76401657, 2.70965883, ..., 4.46877017, 1.18751119,
       2.00940251])

In [28]:
from numpy.random import choice, randint
idx = randint(X.shape[0], size=10)
X_test, y_test = X[idx,:], y[idx]
#X_test1 = X[choice(X.shape[0], 10, replace=False),:]
#X_test1.shape
#y_test1 = y[X_test1.index]


In [35]:
X_test[0,:].tolist()

[4.375,
 16.0,
 4.909090909090909,
 0.8181818181818182,
 54.0,
 2.4545454545454546,
 37.91,
 -120.32]

In [ ]:
X_test1